# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wUo-VbNSulZoR_hm72m8uLEzDTgbT2WY
"""

from fastapi import FastAPI, Request
from transformers import pipeline
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()

# Allow requests from your Flutter app
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # replace with your app domain for security
    allow_methods=["*"],
    allow_headers=["*"],
)

# Load your trained model
classifier = pipeline(
    "text-classification",
    model="C:\\Users\\Magic Systems\\OneDrive\\Desktop\\Emotion_API\\Roberta_model",
    tokenizer="C:\\Users\\Magic Systems\\OneDrive\\Desktop\\Emotion_API\\Roberta_model",
    return_all_scores=True
)


label_map = {
    "LABEL_0": "Happy",
    "LABEL_1": "Sad",
    "LABEL_2": "Surprised",
    "LABEL_3": "Angry"
    
}

@app.post("/predict-emotion")
async def predict(request: Request):
    data = await request.json()
    text = data["text"]
    results = classifier(text)[0]
    top_label = max(results, key=lambda x: x["score"])["label"]
    emotion = label_map.get(top_label, "Unknown")

    return {"emotion": emotion}

